openapi: 3.1.0
info:
  title: Test X-Types described with X-Type
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          description: Test.
          content:
            application/json:
              x-type:
                $ref: ../../x-type.yaml#/XType
              examples:
                WrongAndUsage:
                  value:
                    $and:
                      - {Az: number}
                      - {Bukh: string}
                    wrong: should not be defined along the `$and` keyword!
                CorrectAndUsage:
                  value:
                    $and:
                      - {Az: number}
                      - {Bukh: string}
                WrongArrayUsage:
                  value:
                    $array: string
                    wrong: should not be defined along the `$array` keyword!
                CorrectArrayUsage:
                  value:
                    $array: string
                CorrectPrimitive:
                  value: some-string-literal
                CorrectRecord:
                  value:
                    Az:
                      Bukh:
                        Vidh: # will this conflict with $record: boolean? theoretically it should
                          Glagol: number
                        $record: boolean
                CorrectOr:
                  value:
                    - Az
                    - Bukh: any

components:
  x-types:
    $ref: ../../x-type.yaml # needed for using $refs outside the main document
